### PR TITLE
Migrate to Swift 3

### PR DESCRIPTION
**Pull request by digoreis**
I migrate to Swift 3 and update SwiftJSON .

### CODE REVIEW

**Comment by goingreen** [comment]
Hi! I tried to run project but it crashed when it was creating JSON 😢 Please check that error

**Comment by digoreis** [comment]
I don't have a api key to test . How do I create one ?

**Comment by goingreen** [comment]
You don't need one to test that behavior. Just hit "next" on every screen to get error

**Comment by digoreis** [comment]
Hey Artur , 
I find the problem and resolve . But now , you need API key to test . The JSON return of API : 
{
  "error" : {
    "code" : 400,
    "message" : "API key not valid. Please pass a valid API key.",
    "status" : "INVALID_ARGUMENT",
    "details" : [
      {
        "@type" : "type.googleapis.com\/google.rpc.Help",
        "links" : [
          {
            "url" : "https:\/\/console.developers.google.com",
            "description" : "Google developers console"
          }
        ]
      }
    ]
  }
}
  - rawArray : 0 elements
  ▿ rawDictionary : 1 element
    ▿ 0 : 2 elements
      - .0 : "error"
      ▿ .1 : 4 elements
        ▿ 0 : 2 elements
          - .0 : code
          - .1 : 400
        ▿ 1 : 2 elements
          - .0 : message
          - .1 : API key not valid. Please pass a valid API key.
        ▿ 2 : 2 elements
          - .0 : status
          - .1 : INVALID_ARGUMENT
        ▿ 3 : 2 elements
          - .0 : details
          ▿ .1 : 1 element
            ▿ 0 : 2 elements
              ▿ 0 : 2 elements
                - .0 : @type
                - .1 : type.googleapis.com/google.rpc.Help
              ▿ 1 : 2 elements
                - .0 : links
                ▿ .1 : 1 element
                  ▿ 0 : 2 elements
                    ▿ 0 : 2 elements
                      - .0 : url
                      - .1 : https://console.developers.google.com
                    ▿ 1 : 2 elements
                      - .0 : description
                      - .1 : Google developers console
  - rawString : ""
  - rawBool : false
  - _type : superVision.Type.dictionary
  - _error : nil

**Comment by goingreen** [comment]
I checked it by myself and everything works fine! 👍 Could you please remove debug print and then I'm ready to merge

**Comment by digoreis** [comment]
👍

**Pull request merged**
